# Generated by Django 2.2.9 on 2020-02-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artical',
            name='img',
            field=models.ImageField(upload_to='article_pics'),
        ),
    ]
